export enum UserStatus { ACTIVE = 'ACTIVE', INACTIVE = 'INACTIVE', SUSPENDED = 'SUSPENDED' }
export enum CampaignStatus { DRAFT = 'DRAFT', VALIDATING = 'VALIDATING', QUEUED = 'QUEUED', SENDING = 'SENDING', PAUSED = 'PAUSED', COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED', FAILED = 'FAILED' }
export enum ProviderType { AWS_SES = 'AWS_SES', AZURE_EMAIL = 'AZURE_EMAIL', SMTP = 'SMTP', SENDGRID = 'SENDGRID', MAILGUN = 'MAILGUN' }
export enum VerificationStatus { PENDING = 'PENDING', VERIFIED = 'VERIFIED', FAILED = 'FAILED' }
export enum EmailLogStatus { QUEUED = 'QUEUED', SENDING = 'SENDING', SENT = 'SENT', DELIVERED = 'DELIVERED', OPENED = 'OPENED', CLICKED = 'CLICKED', BOUNCED = 'BOUNCED', COMPLAINED = 'COMPLAINED', FAILED = 'FAILED' }
export enum DeliveryEventType { DELIVERED = 'DELIVERED', BOUNCE_HARD = 'BOUNCE_HARD', BOUNCE_SOFT = 'BOUNCE_SOFT', COMPLAINT = 'COMPLAINT', OPEN = 'OPEN', CLICK = 'CLICK', UNSUBSCRIBE = 'UNSUBSCRIBE' }
export enum AuditAction { CREATE = 'CREATE', UPDATE = 'UPDATE', DELETE = 'DELETE', LOGIN = 'LOGIN', LOGOUT = 'LOGOUT', SEND = 'SEND', CONFIGURE = 'CONFIGURE', GRANT_ACCESS = 'GRANT_ACCESS', REVOKE_ACCESS = 'REVOKE_ACCESS' }
